### ISSUE TITLE
log in

### ISSUE THREAD

**Issue by devpato** [pevargasg/jobersity#1]
This are the link I was working on with 

http://localhost:3000/users/new*
http://localhost:3000/login
http://localhost:3000/admin*
http://localhost:3000/users*

The ones with the start are the ones that are woking. I even checked the db and the user is there when I created it and in the admin page shows me how many users I have. After this Is done I was thinking on using the code in the ("iniciar sesion") "log in" button in the index page the one that has all the bootstrap etc @mtcliatt

**Comment by mtcliatt** [comment]
The problem was with the form_tag in the users view new.html.erb. I'm not sure what the default it, but apparently you need to add in the route that the form should send to, and the method (post). This is the only line change that even mattered:

`form_tag("/search", method: "get") do`
